---
- name: converge | all
  hosts: all
  remote_user: root
  become: true
  gather_facts: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: ansible-role-crun
      tags: buluma.crun
