---
- name: Verify | all
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: crun --version
      ansible.builtin.command:
        cmd: crun --version
      register: result
      changed_when: result is not succeeded
